### ISSUE TITLE
Roadmap of the game.

### ISSUE THREAD

**Issue by RichardPaulAstley** [RichardPaulAstley/richardpaulastley.github.io#22]
Let's go, now that the game is updating almost everyday, it's time to see things in the long term. And to be ready to release something amazing. Here's the basic roadmap : 

- [x] Fixing the Catch Rate
- [x] 802 Pokemon
- [x] 7 Regions
- [x] Adding more control in Catching Pokemon
- [x] Adding Shiny Probability
- [x] Saving System (PokeClickers like)
- [x] Manage Team upgrade
- [x] Catching only NEW Pokemon
- [x] New Battle system

Let's go for BONUS goals once the main goals are done : 

Discussion needed : 

- [x] Statistics Counter (Important)

**Comment by freitagdavid** [comment]
So is only catching uncaught pokemon one of the ideas for more control in catching pokemon.

**Comment by RichardPaulAstley** [comment]
We are done. Only bug fixes, a thing to add one day and new Pokemon support are planned.
